# Generated by Django 4.0.3 on 2022-04-28 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntajeArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
            ],
            options={
                'db_table': 'puntaje_tarea',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tipo_archivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tarea',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('directorio', models.CharField(max_length=100)),
                ('id_puntaje_archivo', models.ForeignKey(db_column='id_puntaje_archivo', on_delete=django.db.models.deletion.CASCADE, to='tareas.puntajearchivo')),
                ('id_tarea', models.ForeignKey(blank=True, db_column='id_tarea', null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.tarea')),
                ('id_tipo_archivo', models.ForeignKey(db_column='id_tipo_archivo', on_delete=django.db.models.deletion.CASCADE, to='tareas.tipoarchivo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archivo',
                'managed': True,
            },
        ),
    ]
