# Generated by Django 4.0.3 on 2022-06-11 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='id_tarea',
            field=models.ForeignKey(db_column='id_tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.tarea'),
        ),
        migrations.AlterField(
            model_name='foro',
            name='id_tipo_foro',
            field=models.ForeignKey(db_column='id_tipo_foro', on_delete=django.db.models.deletion.PROTECT, to='tareas.tipoforo'),
        ),
    ]
