# Generated by Django 4.0.3 on 2022-06-17 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='id_actividad',
            field=models.ForeignKey(db_column='id_actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.actividad', unique=True),
        ),
    ]
