# Generated by Django 4.0.3 on 2022-06-18 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_delete_puntaje'),
        ('tareas', '0002_alter_foro_id_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.SmallIntegerField()),
                ('id_tipo_actividad', models.ForeignKey(db_column='id_tipo_actividad', on_delete=django.db.models.deletion.CASCADE, related_name='puntajes_tipos', to='tareas.tipoactividad')),
            ],
            options={
                'db_table': 'puntaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuario_actividad',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='usuarios',
            field=models.ManyToManyField(related_name='actividades', through='tareas.UsuarioActividad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='id_tipo_actividad',
            field=models.ForeignKey(db_column='id_tipo_actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_tipos', to='tareas.tipoactividad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuarioactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.actividad'),
        ),
        migrations.AddField(
            model_name='usuarioactividad',
            name='puntaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.puntaje'),
        ),
        migrations.AddField(
            model_name='usuarioactividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
