# Generated by Django 4.0.3 on 2022-06-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_puntaje_usuarioactividad_actividad_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioactividad',
            name='puntaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.puntaje'),
        ),
    ]
