# Generated by Django 4.0.3 on 2022-06-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_alter_actividad_id_tipo_actividad'),
        ('tareas', '0007_alter_archivo_id_usuario'),
    ]

    operations = [
    ]
