# Generated by Django 4.0.3 on 2022-06-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_merge_20220623_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
