# Generated by Django 4.0.3 on 2022-07-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_archivo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Foro',
        ),
        migrations.DeleteModel(
            name='TipoForo',
        ),
    ]
