# Generated by Django 4.0.3 on 2022-08-25 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0011_alter_archivo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='fecha',
        ),
    ]
