# Generated by Django 4.0.3 on 2022-08-25 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0012_remove_archivo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
