# Generated by Django 4.0.3 on 2022-06-20 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0010_delete_evaluacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_crea_ev', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PuntajeEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'puntaje_evaluacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion')),
                ('puntaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.puntajeevaluacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_evaluacion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='usuarios',
            field=models.ManyToManyField(related_name='usuario_evaluaciones', through='evaluacion.UsuarioEvaluacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
