# Generated by Django 4.0.3 on 2022-04-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellidoPaterno', models.CharField(max_length=250)),
                ('apellidoMaterno', models.CharField(max_length=250)),
            ],
        ),
    ]
