# Generated by Django 4.0.3 on 2022-04-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tipousuario_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
