# Generated by Django 4.0.3 on 2022-05-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notificacion_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': True,
            },
        ),
    ]
