# Generated by Django 4.0.3 on 2022-05-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
