# Generated by Django 4.0.3 on 2022-05-24 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_archivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField()),
                ('titulo', models.TextField()),
                ('detalles', models.TextField()),
                ('fecha', models.DateField(auto_now=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Archivos',
        ),
    ]
