# Generated by Django 4.0.3 on 2022-06-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_puntaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puntaje',
        ),
    ]
