# Generated by Django 4.0.3 on 2022-06-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_puntaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
