# Generated by Django 4.0.3 on 2022-07-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
