# Generated by Django 4.0.3 on 2022-08-27 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_notificacion_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'estado_notificacion',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='asunto',
            field=models.CharField(default='asunto', max_length=40),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='enviado_por',
            field=models.ForeignKey(db_column='enviado_por', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificacionEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_a', models.ForeignKey(db_column='enviado_a', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.DO_NOTHING, to='app.estadonotificacion')),
            ],
            options={
                'db_table': 'notificacion_enviada',
                'managed': True,
            },
        ),
    ]
