# Generated by Django 4.0.3 on 2022-08-27 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_estadonotificacion_remove_notificacion_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionenviada',
            name='notificacion',
            field=models.ForeignKey(db_column='notificacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.notificacion'),
        ),
        migrations.AlterField(
            model_name='notificacionenviada',
            name='enviado_a',
            field=models.ForeignKey(db_column='enviado_a', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacionenviada',
            name='estado',
            field=models.ForeignKey(db_column='estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.estadonotificacion'),
        ),
    ]
