# Generated by Django 4.0.3 on 2022-10-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_notificacionenviada_notificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionenviada',
            name='estado',
            field=models.ForeignKey(db_column='estado', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.estadonotificacion'),
        ),
    ]
