# Generated by Django 4.0.3 on 2022-06-22 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0010_delete_evaluacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
            ],
            options={
                'db_table': 'asistencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=30)),
                ('puntaje', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'tipo_asistencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.asistencia')),
                ('tipo_asistencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencia.tipoasistencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_asistencia',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='usuarios',
            field=models.ManyToManyField(related_name='usuario_asistencias', through='asistencia.UsuarioAsistencia', to=settings.AUTH_USER_MODEL),
        ),
    ]
