# Generated by Django 4.0.3 on 2022-07-12 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0010_alter_archivo_fecha_delete_foro_delete_tipoforo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('id_actividad', models.ForeignKey(db_column='id_actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.actividad', unique=True)),
            ],
            options={
                'db_table': 'foro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_foro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RespuestaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_foro', models.ForeignKey(db_column='id_foro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foro.foro')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'respuesta_foro',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='foro',
            name='id_tipo_foro',
            field=models.ForeignKey(db_column='id_tipo_foro', on_delete=django.db.models.deletion.PROTECT, to='foro.tipoforo'),
        ),
    ]
