# Generated by Django 4.0.3 on 2022-08-25 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_alter_respuestaforo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
